name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0'

      - name: Installer les dépendances
        run: npm install

      - name: Compiler l'application
        run: npm run build

      - name: Exécuter les tests unitaires
        run: npm test
