name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Vérifier le code
        uses: actions/checkout@v2

      - name: Installer Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.18.0' # Remplacez '14' par la version de Node.js que vous utilisez

      - name: Installer les dépendances
        run: npm install

      - name: Compiler l'application
        run: npm run build # Assurez-vous que votre commande de build est correcte

      - name: Exécuter les tests unitaires
        run: npm test
