name: Node.js Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.18.0' 

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build Docker Image 
      run: docker build -t ${{ secrets.DOCKER_USER }}/pubApp:latest -t ghcr.io/${{ secrets.GHCR_USER }}/pubApp:latest .

    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

    - name: Login to GitHub Container Registry
      env:
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        GHCR_USERNAME: ${{ secrets.GHCR_USER }}
      run: |
        echo "${GHCR_TOKEN}" | docker login ghcr.io -u "${GHCR_USERNAME}" --password-stdin

    - name: Push Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USER }}/pubApp:latest

    - name: Push Image to GitHub Container Registry
      run: docker push ghcr.io/${{ secrets.GHCR_USER }}/pubApp:latest